package com.example.freetuts.model;

// default package
// Generated Jan 28, 2019 1:44:07 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * DiemThi generated by hbm2java
 */
@Entity
@Table(name = "diem_thi", catalog = "ql_sv")
@IdClass(DiemThiId.class)
public class DiemThi implements java.io.Serializable {
	@Id
	private int maMh;
	@Id
	private int maSv;
	private Float diemLan1;
	private Float diemLan2;

	public DiemThi() {
	}

	


	public DiemThi(int maMh, int maSv, Float diemLan1, Float diemLan2) {
		super();
		this.maMh = maMh;
		this.maSv = maSv;
		this.diemLan1 = diemLan1;
		this.diemLan2 = diemLan2;
	}
	
	



	@Column(name="MaMh")
	public int getMaMh() {
		return maMh;
	}



	@Column(name="MaSV")
	public void setMaMh(int maMh) {
		this.maMh = maMh;
	}




	public int getMaSv() {
		return maSv;
	}




	public void setMaSv(int maSv) {
		this.maSv = maSv;
	}




	@Column(name = "DiemLan1", precision = 12, scale = 0)
	public Float getDiemLan1() {
		return this.diemLan1;
	}

	public void setDiemLan1(Float diemLan1) {
		this.diemLan1 = diemLan1;
	}

	@Column(name = "DiemLan2", precision = 12, scale = 0)
	public Float getDiemLan2() {
		return this.diemLan2;
	}

	public void setDiemLan2(Float diemLan2) {
		this.diemLan2 = diemLan2;
	}

}
