package com.example.freetuts.model;

// default package
// Generated Jan 22, 2019 7:27:24 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MonhocLop generated by hbm2java
 */
@Entity
@Table(name = "monhoc_lop", catalog = "ql_sv")
@IdClass(MonhocLopId.class)
public class MonhocLop implements java.io.Serializable {
	@Id
	@Column(name = "ma_lop")
	private int maLop;
	@Id
	@Column(name = "ma_mh")
	private int maMh;

	

	public MonhocLop() {
	}

	public MonhocLop(int maLop,int maMh) {
		this.maLop=maLop;
		this.maMh=maMh;
	}


	public int getMaLop() {
		return this.maLop;
	}

	public void setMaLop(int maLop) {
		this.maLop = maLop;
	}

	
	public int getMaMh() {
		return this.maMh;
	}

	public void setMaMh(int maMh) {
		this.maMh = maMh;
	}


	
	
	


}
