package com.example.freetuts.model;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated Jan 22, 2019 7:27:24 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MonHoc generated by hbm2java
 */
@Entity
@Table(name = "mon_hoc", catalog = "ql_sv")
public class MonHoc implements java.io.Serializable {

	private int maMh;
	private String tenMh;
	
	public MonHoc() {
	}

	public MonHoc(int maMh) {
		this.maMh = maMh;
	}

	public MonHoc(int maMh, String tenMh) {
		this.maMh = maMh;
		this.tenMh = tenMh;
	
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Ma_mh", unique = true, nullable = false)
	public int getMaMh() {
		return this.maMh;
	}

	public void setMaMh(int maMh) {
		this.maMh = maMh;
	}

	@Column(name = "ten_mh", length = 45)
	public String getTenMh() {
		return this.tenMh;
	}

	public void setTenMh(String tenMh) {
		this.tenMh = tenMh;
	}





}
