package com.example.freetuts.model;

// default package
// Generated Jan 22, 2019 7:27:24 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MonhocLopId generated by hbm2java
 */

public class MonhocLopId implements java.io.Serializable {

	private int maLop;
	private int maMh;

	public MonhocLopId() {
	}

	public MonhocLopId(int maLop, int maMh) {
		this.maLop = maLop;
		this.maMh = maMh;
	}

	public int getMaLop() {
		return this.maLop;
	}


	
	public int getMaMh() {
		return this.maMh;
	}

	

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MonhocLopId))
			return false;
		MonhocLopId castOther = (MonhocLopId) other;

		return (this.getMaLop() == castOther.getMaLop()) && (this.getMaMh() == castOther.getMaMh());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaLop();
		result = 37 * result + this.getMaMh();
		return result;
	}

}
