package com.example.demo.model;

// default package
// Generated Jan 29, 2019 10:54:08 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier", catalog = "ban_hang")
public class Supplier implements java.io.Serializable {

	private Integer supplierId;
	private String companyName;
	private String address;
	private String phone;


	public Supplier() {
	}

	public Supplier(String companyName, String address, String phone) {
		this.companyName = companyName;
		this.address = address;
		this.phone = phone;
	
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SupplierID", unique = true, nullable = false)
	public Integer getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	@Column(name = "CompanyName", length = 45)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "Address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "Phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	

}
