package com.example.database.entity;

// default package
// Generated Jan 31, 2019 10:14:08 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "ban_hang")
public class Category implements java.io.Serializable {

	private Integer categoryId;
	private String categoryName;
	private String description;
	private String picture;
	

	public Category() {
	}

	public Category(String categoryName, String description, String picture) {
		this.categoryName = categoryName;
		this.description = description;
		this.picture = picture;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CategoryID", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "CategoryName", length = 45)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "Description", length = 16777215)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Picture", length = 45)
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	

}
