package com.example.database.entity;

// default package
// Generated Jan 31, 2019 10:14:08 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "customers", catalog = "ban_hang")
public class Customers implements java.io.Serializable {

	private Integer customerId;
	private String name;
	private String address;
	private String phone;
	

	public Customers() {
	}

	public Customers(String name, String address, String phone) {
		this.name = name;
		this.address = address;
		this.phone = phone;
	
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CustomerID", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "Name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "Phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	

}
