package com.example.database.entity;

// default package
// Generated Jan 31, 2019 10:14:08 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "employees", catalog = "ban_hang")
public class Employees implements java.io.Serializable {

	private Integer employeeId;
	private String lastName;
	private String firstName;
	private Date birthDate;
	private String hireDate;
	private String address;
	private String phone;

	public Employees() {
	}

	public Employees(String lastName, String firstName, Date birthDate, String hireDate, String address, String phone) {
		this.lastName = lastName;
		this.firstName = firstName;
		this.birthDate = birthDate;
		this.hireDate = hireDate;
		this.address = address;
		this.phone = phone;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EmployeeID", unique = true, nullable = false)
	public Integer getEmployeeId() {
		return this.employeeId;
	}
	public void setEmployeeId(int employeeId)
	{
		this.employeeId =employeeId;
	}



	@Column(name = "LastName", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "FirstName", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BirthDate", length = 26)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "HireDate", length = 45)
	public String getHireDate() {
		return this.hireDate;
	}

	public void setHireDate(String hireDate) {
		this.hireDate = hireDate;
	}

	@Column(name = "Address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "Phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	

}
