package com.example.database.entity;

// default package
// Generated Jan 31, 2019 10:14:08 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderDetailsId generated by hbm2java
 */

public class OrderDetailsId implements java.io.Serializable {

	private int ordersId;
	private int productId;

	public OrderDetailsId() {
	}

	public OrderDetailsId(int orderId, int productId) {
		this.ordersId = orderId;
		this.productId = productId;
	}

//	@Column(name = "OrderID", nullable = false)
//	public int getOrderId() {
//		return this.ordersId;
//	}
//
//	public void setOrderId(int orderId) {
//		this.ordersId = orderId;
//	}
//
//	@Column(name = "ProductID", nullable = false)
//	public int getProductId() {
//		return this.productId;
//	}
//
//	public void setProductId(int productId) {
//		this.productId = productId;
//	}
//
//	public boolean equals(Object other) {
//		if ((this == other))
//			return true;
//		if ((other == null))
//			return false;
//		if (!(other instanceof OrderDetailsId))
//			return false;
//		OrderDetailsId castOther = (OrderDetailsId) other;
//
//		return (this.getOrderId() == castOther.getOrderId()) && (this.getProductId() == castOther.getProductId());
//	}
//
//	public int hashCode() {
//		int result = 17;
//
//		result = 37 * result + this.getOrderId();
//		result = 37 * result + this.getProductId();
//		return result;
//	}

}
