package com.example.database.entity;

// default package
// Generated Jan 31, 2019 10:14:08 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name = "order_details", catalog = "ban_hang")
@IdClass(OrderDetailsId.class)
public class OrderDetails implements java.io.Serializable {

	@Id
	@Column(name = "OrderID")
	private int ordersId;
	@Id
	@Column(name = "ProductID")
	private int productId;

	private String unitPrice;
	private String quantity;

	public OrderDetails() {
	}


	public OrderDetails(int orders, int product, String unitPrice, String quantity) {
		
		this.ordersId = orders;
		this.productId = product;
		
		this.unitPrice = unitPrice;
		this.quantity = quantity;
	}




	
	
	public int getOrdersId() {
		return this.ordersId;
	}

	public void setOrders(int orders) {
		this.ordersId = orders;
	}

	
	
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int product) {
		this.productId = product;
	}

	@Column(name = "UnitPrice", length = 45)
	public String getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(String unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "Quantity", length = 45)
	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

}
