package com.example.database.entity;

// default package
// Generated Jan 31, 2019 10:14:08 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "ban_hang")
public class Product implements java.io.Serializable {

	private Integer productId;
	private int categoryId;
	private int supplierId;
	private String productName;
	private Integer quatity;
	private Integer unitPrice;
	

	public Product() {
	}

	public Product(int categoryId, int supplierId, String productName, Integer quatity, Integer unitPrice) {
		this.categoryId = categoryId;
		this.supplierId = supplierId;
		this.productName = productName;
		this.quatity = quatity;
		this.unitPrice = unitPrice;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ProductID", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	
	@Column(name = "CategoryID")
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	
	@Column(name = "SupplierID")
	public int getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(int supplierId) {
		this.supplierId = supplierId;
	}

	@Column(name = "ProductName", length = 45)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "Quatity")
	public Integer getQuatity() {
		return this.quatity;
	}

	public void setQuatity(Integer quatity) {
		this.quatity = quatity;
	}

	@Column(name = "UnitPrice")
	public Integer getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Integer unitPrice) {
		this.unitPrice = unitPrice;
	}

	

}
